from typing import Any

default_appearance: dict[str: Any] = {
    "figsize": None,
    "dpi": 100,
    "pr_marker": {"high": 's', "medium": 'o', "low": '.'},
    "pr_markercolor": {"high": "red", "medium": "purple", "low": "black"},
    "pr_markersize": 400.0,
    "pr_linecolor": 'k',
    "pr_linestyle": "solid",
    "pr_linewidth": 1.0,
    "pr_position": [0.05, 0.75, 0.9, 0.3],
    "title_fontsize": 30.0,
    "title_fontweight": "bold",
    "title_fontcolor": 'k',
    "title_fontfamily": "Times New Roman",
    "title_va": "center",
    "title_ha": "center",
    "stations_fontsize": 25.0,
    "stations_fontweight": "bold",
    "stations_fontcolor": 'k',
    "stations_fontstyle": "normal",
    "stations_fontfamily": "Times New Roman",
    "stations_ha": "center",
    "stations_va": "center",
    "lines_marker": 'o',
    "lines_markersize": 10.0,
    "lines_color": 'b',
    "lines_linestyle": "solid",
    "lines_linewidth": 3.0,
    "lines_position": [0.05, 0.05, 0.9, 0.83],
    "arrow_length": 0.3,
    "arrow_width": 0.2,
    "ticks_fontsize": 20.0,
    "ticks_fontcolor": 'k',
    "ticks_fontfamily": "Times New Roman",
    "sta_pr_spacing": 0.005,
    "title_pr_spacing": 0.02
    }

